<?php
/**
 * Title: All Blocks Demo
 * Slug: bvdb/all-blocks-demo
 * Description: This pattern is to show all blocks
 * Categories: demo-blocks
 * Keywords: Demo
 * Viewport Width: 1280
 * Block Types: 
 * Post Types: 
 * Inserter: true
 * Custom Categories: Demo Blocks
 */
register_block_pattern_category( 'demo-blocks', [ 'label' => __( 'Demo Blocks', 'bvdb' ), 'pm_custom' => true ] );
?>
<!-- wp:acf/hero {"name":"acf/hero","data":{"title_text":"This is a Hero Block","_title_text":"field_64af639d1da5e","title_type":"h2","_title_type":"field_64af63d01da5f","title":"","_title":"field_64af644e3b3e1","copy":"\u003cp\u003eIpsum tempor aliqua cillum ex nisi pariatur officia ad pariatur id. Ullamco nulla sunt magna non do aliqua. Irure proident incididunt ipsum tempor aliqua. Ullamco non esse tempor excepteur qui velit tempor aliqua irure irure veniam laboris. Culpa veniam labore sunt veniam aute anim labore ea officia et aute.\u003c/p\u003e","_copy":"field_6470619f70d36","button_button":{"title":"Call To Action","url":"#","target":""},"_button_button":"field_64b46ff5cdb2f","button_variant":"primary","_button_variant":"field_64b47013cdb30","button":"","_button":"field_64b477c161265","image":16,"_image":"field_647061bd70d38"},"align":"full","mode":"preview","fullHeight":false} /-->

<!-- wp:acf/content {"name":"acf/content","data":{"heading_text":"This is a content Block","_heading_text":"field_64af639d1da5e","heading_type":"h2","_heading_type":"field_64af63d01da5f","heading":"","_heading":"field_65e53ef54f3b6","content":"Ipsum tempor aliqua cillum ex nisi pariatur officia ad pariatur id. Ullamco nulla sunt magna non do aliqua. Irure proident incididunt ipsum tempor aliqua. Ullamco non esse tempor excepteur qui velit tempor aliqua irure irure veniam laboris. Culpa veniam labore sunt veniam aute anim labore ea officia et aute.Ipsum tempor aliqua cillum ex nisi pariatur officia ad pariatur id. Ullamco nulla sunt magna non do aliqua. Irure proident incididunt ipsum tempor aliqua. Ullamco non esse tempor excepteur qui velit tempor aliqua irure irure veniam laboris. Culpa veniam labore sunt veniam aute anim labore ea officia et aute.","_content":"field_65e53ef54f3b9","content_options_columns":"1","_content_options_columns":"field_65e53ef5508a4","content_options":"","_content_options":"field_65e53ef54f3bc"},"align":"full","mode":"preview","alignText":"left"} /-->

<!-- wp:acf/video-text {"name":"acf/video-text","data":{"heading_text":"This is an Text \u0026 Video Block","_heading_text":"field_64af639d1da5e","heading_type":"h2","_heading_type":"field_64af63d01da5f","heading":"","_heading":"field_64706bfed116e","copy":"Ipsum tempor aliqua cillum ex nisi pariatur officia ad pariatur id. Ullamco nulla sunt magna non do aliqua. Irure proident incididunt ipsum tempor aliqua. Ullamco non esse tempor excepteur qui velit tempor aliqua irure irure veniam laboris. Culpa veniam labore sunt veniam aute anim labore ea officia et aute.","_copy":"field_64706bfed1176","button_button":{"title":"Call To Action","url":"#","target":""},"_button_button":"field_64b46ff5cdb2f","button_variant":"secondary","_button_variant":"field_64b47013cdb30","button":"","_button":"field_64706bfed117d","reverse":"0","_reverse":"field_64706bfed1185","video_video_source":"oembed","_video_video_source":"field_65fa8e76ca303","video_video_oembed":"https://www.youtube.com/watch?v=hxXZG6U9Yjw","_video_video_oembed":"field_65fa8e76ca309","video":"","_video":"field_65fa9287c94ff"},"align":"full","mode":"preview","alignText":"left","alignContent":"top"} /-->

<!-- wp:acf/image {"name":"acf/image","data":{"image":122,"_image":"field_64b5bf98fefcb"},"align":"full","mode":"preview"} /-->

<!-- wp:acf/team {"name":"acf/team","data":{"heading_text":"This is a Team Block","_heading_text":"field_64af639d1da5e","heading_type":"h2","_heading_type":"field_64af63d01da5f","heading":"","_heading":"field_6475b6d1c56b2","copy":"Labore deserunt mollit irure elit. Mollit ut ut commodo. Laboris deserunt mollit reprehenderit.","_copy":"field_6475b6e2c56b3","team":["1"],"_team":"field_6475b6f0c56b4"},"align":"full","mode":"preview"} /-->

<!-- wp:acf/cta {"name":"acf/cta","data":{"heading_text":"This is an call to action block","_heading_text":"field_64af639d1da5e","heading_type":"h2","_heading_type":"field_64af63d01da5f","heading":"","_heading":"field_647594d21e97f","copy":"Labore deserunt mollit irure elit. Mollit ut ut commodo. Laboris deserunt mollit reprehenderit. Officia irure dolor sint reprehenderit esse dolore aliquip reprehenderit ad duis incididunt est. Deserunt dolor ad labore magna amet non culpa anim aute eu reprehenderit esse ea tempor. Elit nostrud cillum ut anim incididunt occaecat culpa quis consequat sint commodo. In non occaecat quis dolore commodo ullamco labore ex minim. Commodo tempor commodo elit.","_copy":"field_647594de1e980","buttons_0_button":{"title":"Call To Action","url":"#","target":""},"_buttons_0_button":"field_64b4705b41a63_field_64b46ff5cdb2f","buttons_0_variant":"primary","_buttons_0_variant":"field_64b4705b41a63_field_64b47013cdb30","buttons_1_button":{"title":"Content","url":"#","target":""},"_buttons_1_button":"field_64b4705b41a63_field_64b46ff5cdb2f","buttons_1_variant":"link","_buttons_1_variant":"field_64b4705b41a63_field_64b47013cdb30","buttons":2,"_buttons":"field_64759561807da"},"align":"full","mode":"preview"} /-->

<!-- wp:acf/image-text {"name":"acf/image-text","data":{"heading_text":"This is an Image \u0026 Text block","_heading_text":"field_64af639d1da5e","heading_type":"h2","_heading_type":"field_64af63d01da5f","heading":"","_heading":"field_64706409c4f96","copy":"Labore deserunt mollit irure elit. Mollit ut ut commodo. Laboris deserunt mollit reprehenderit. Officia irure dolor sint reprehenderit esse dolore aliquip reprehenderit ad duis incididunt est. Deserunt dolor ad labore magna amet non culpa anim aute eu reprehenderit esse ea tempor. Elit nostrud cillum ut anim incididunt occaecat culpa quis consequat sint commodo. In non occaecat quis dolore commodo ullamco labore ex minim. Commodo tempor commodo elit.\r\n\r\nLabore deserunt mollit irure elit. Mollit ut ut commodo. Laboris deserunt mollit reprehenderit. Officia irure dolor sint reprehenderit esse dolore aliquip reprehenderit ad duis incididunt est. Deserunt dolor ad labore magna amet non culpa anim aute eu reprehenderit esse ea tempor. Elit nostrud cillum ut anim incididunt occaecat culpa quis consequat sint commodo. In non occaecat quis dolore commodo ullamco labore ex minim. Commodo tempor commodo elit.\r\n\r\nLabore deserunt mollit irure elit. Mollit ut ut commodo. Laboris deserunt mollit reprehenderit. Officia irure dolor sint reprehenderit esse dolore aliquip reprehenderit ad duis incididunt est. Deserunt dolor ad labore magna amet non culpa anim aute eu reprehenderit esse ea tempor. Elit nostrud cillum ut anim incididunt occaecat culpa quis consequat sint commodo. In non occaecat quis dolore commodo ullamco labore ex minim. Commodo tempor commodo elit.","_copy":"field_64706409c4f9e","button_button":{"title":"Call To Action","url":"#","target":""},"_button_button":"field_64b46ff5cdb2f","button_variant":"secondary","_button_variant":"field_64b47013cdb30","button":"","_button":"field_64706409c4fa2","image":571,"_image":"field_64706409c4fa6","reverse":"0","_reverse":"field_647068690ac39","crop":"1","_crop":"field_66456b730dcf2"},"align":"full","mode":"preview","alignText":"left","alignContent":"top"} /-->

<!-- wp:acf/description-list {"name":"acf/description-list","data":{"heading_text":"This is an Description List Block","_heading_text":"field_64af639d1da5e","heading_type":"h2","_heading_type":"field_64af63d01da5f","heading":"","_heading":"field_6475c53f66e4e","copy":"Labore deserunt mollit irure elit. Mollit ut ut commodo. Laboris deserunt mollit reprehenderit. Officia irure dolor sint reprehenderit esse dolore aliquip reprehenderit ad duis incididunt est. Deserunt dolor ad labore magna amet non culpa anim aute eu reprehenderit esse ea tempor. Elit nostrud cillum ut anim incididunt occaecat culpa quis consequat sint commodo. In non occaecat quis dolore commodo ullamco labore ex minim. Commodo tempor commodo elit.","_copy":"field_6475c54c66e4f","list_items_0_dt":"Consequat elit et deserunt consectetur ipsum amet aliquip non cupidatat sint excepteur magna.","_list_items_0_dt":"field_6475c57166e51","list_items_0_dd":"Labore deserunt mollit irure elit. Mollit ut ut commodo. Laboris deserunt mollit reprehenderit. Officia irure dolor sint reprehenderit esse dolore aliquip reprehenderit ad duis incididunt est. Deserunt dolor ad labore magna amet non culpa anim aute eu reprehenderit esse ea tempor. Elit nostrud cillum ut anim incididunt occaecat culpa quis consequat sint commodo. In non occaecat quis dolore commodo ullamco labore ex minim. Commodo tempor commodo elit.","_list_items_0_dd":"field_6475c58566e52","list_items_1_dt":"Culpa cupidatat ex eu non ullamco sit ea exercitation sit sunt dolor aute sint id occaecat.","_list_items_1_dt":"field_6475c57166e51","list_items_1_dd":"Labore deserunt mollit irure elit. Mollit ut ut commodo. Laboris deserunt mollit reprehenderit. Officia irure dolor sint reprehenderit esse dolore aliquip reprehenderit ad duis incididunt est. Deserunt dolor ad labore magna amet non culpa anim aute eu reprehenderit esse ea tempor. Elit nostrud cillum ut anim incididunt occaecat culpa quis consequat sint commodo. In non occaecat quis dolore commodo ullamco labore ex minim. Commodo tempor commodo elit.","_list_items_1_dd":"field_6475c58566e52","list_items_2_dt":"Sit ipsum non sunt consequat duis commodo quis non elit nostrud.","_list_items_2_dt":"field_6475c57166e51","list_items_2_dd":"Labore deserunt mollit irure elit. Mollit ut ut commodo. Laboris deserunt mollit reprehenderit. Officia irure dolor sint reprehenderit esse dolore aliquip reprehenderit ad duis incididunt est. Deserunt dolor ad labore magna amet non culpa anim aute eu reprehenderit esse ea tempor. Elit nostrud cillum ut anim incididunt occaecat culpa quis consequat sint commodo. In non occaecat quis dolore commodo ullamco labore ex minim. Commodo tempor commodo elit.","_list_items_2_dd":"field_6475c58566e52","list_items":3,"_list_items":"field_6475c56166e50"},"align":"full","mode":"preview"} /-->

<!-- wp:acf/video {"name":"acf/video","data":{"video_source":"oembed","_video_source":"field_65fa8e76ca303","video_oembed":"https://www.youtube.com/watch?v=hxXZG6U9Yjw","_video_oembed":"field_65fa8e76ca309","video":"","_video":"field_660c1f9cb0f12"},"align":"full","mode":"preview"} /-->

<!-- wp:acf/newsletter {"name":"acf/newsletter","data":{"text":"This is a Newsletter Block","_text":"field_64af639d1da5e","type":"h2","_type":"field_64af63d01da5f","heading":"","_heading":"field_6475ce93d8c5f","policy":"Ipsum id id ullamco labore mollit mollit aute est aliqua labore laborum sunt deserunt in. Cupidatat proident excepteur fugiat in reprehenderit exercitation esse do reprehenderit laborum Lorem id amet nisi. Ipsum laborum sit anim non fugiat ipsum aliquip fugiat nisi incididunt. Cillum aliquip eu occaecat excepteur mollit aute laboris cupidatat ullamco ex Lorem duis. Nulla exercitation do dolore commodo commodo pariatur exercitation laboris do anim reprehenderit laboris pariatur amet dolore.","_policy":"field_6475cf059e9b9"},"align":"full","mode":"preview"} /-->

<!-- wp:acf/faq {"name":"acf/faq","data":{"heading_text":"This is a FAQ Block","_heading_text":"field_64af639d1da5e","heading_type":"h2","_heading_type":"field_64af63d01da5f","heading":"","_heading":"field_6475bceb7ea5d","faq_0_question":"Mollit incididunt qui esse occaecat qui est exercitation Lorem pariatur adipisicing elit.","_faq_0_question":"field_6475bd67a7ddd","faq_0_answer":"Ipsum id id ullamco labore mollit mollit aute est aliqua labore laborum sunt deserunt in. Cupidatat proident excepteur fugiat in reprehenderit exercitation esse do reprehenderit laborum Lorem id amet nisi. Ipsum laborum sit anim non fugiat ipsum aliquip fugiat nisi incididunt. Cillum aliquip eu occaecat excepteur mollit aute laboris cupidatat ullamco ex Lorem duis. Nulla exercitation do dolore commodo commodo pariatur exercitation laboris do anim reprehenderit laboris pariatur amet dolore.","_faq_0_answer":"field_6475bd74a7dde","faq_1_question":"Duis aute proident ut ad reprehenderit quis cupidatat incididunt velit veniam.","_faq_1_question":"field_6475bd67a7ddd","faq_1_answer":"Ipsum id id ullamco labore mollit mollit aute est aliqua labore laborum sunt deserunt in. Cupidatat proident excepteur fugiat in reprehenderit exercitation esse do reprehenderit laborum Lorem id amet nisi. Ipsum laborum sit anim non fugiat ipsum aliquip fugiat nisi incididunt. Cillum aliquip eu occaecat excepteur mollit aute laboris cupidatat ullamco ex Lorem duis. Nulla exercitation do dolore commodo commodo pariatur exercitation laboris do anim reprehenderit laboris pariatur amet dolore.","_faq_1_answer":"field_6475bd74a7dde","faq_2_question":"Aliqua sunt et ex occaecat non laborum cupidatat exercitation et fugiat nisi sint ad.","_faq_2_question":"field_6475bd67a7ddd","faq_2_answer":"Ipsum id id ullamco labore mollit mollit aute est aliqua labore laborum sunt deserunt in. Cupidatat proident excepteur fugiat in reprehenderit exercitation esse do reprehenderit laborum Lorem id amet nisi. Ipsum laborum sit anim non fugiat ipsum aliquip fugiat nisi incididunt. Cillum aliquip eu occaecat excepteur mollit aute laboris cupidatat ullamco ex Lorem duis. Nulla exercitation do dolore commodo commodo pariatur exercitation laboris do anim reprehenderit laboris pariatur amet dolore.","_faq_2_answer":"field_6475bd74a7dde","faq":3,"_faq":"field_6475bd5ca7ddc"},"align":"full","mode":"preview"} /-->

<!-- wp:acf/features {"name":"acf/features","data":{"heading_text":"This is a Features Block","_heading_text":"field_64af639d1da5e","heading_type":"h2","_heading_type":"field_64af63d01da5f","heading":"","_heading":"field_64759ac5d4a4d","copy":"Mollit incididunt qui esse occaecat qui est exercitation Lorem pariatur adipisicing elit.Consequat labore id aliquip culpa laboris qui aliqua reprehenderit sint occaecat minim elit aliqua. Veniam enim labore quis id nisi. Velit mollit sunt incididunt esse elit esse officia tempor exercitation qui sit eiusmod amet. Mollit eu eu consectetur ipsum et nulla velit cupidatat anim sunt nisi proident elit nisi.","_copy":"field_64759c6bd4a4f","features_0_heading":"Ea fugiat Lorem dolore cillum proident proident eiusmod adipisicing et et.","_features_0_heading":"field_64759cced4a51","features_0_copy":"Irure velit enim dolore elit ullamco Lorem amet aliquip occaecat ipsum proident. Do eu exercitation reprehenderit do laboris aliqua eu aliquip eu ea tempor sunt. Fugiat cillum cillum officia aliqua incididunt ex occaecat quis exercitation ad eiusmod cupidatat officia. Cillum consequat anim esse culpa.","_features_0_copy":"field_64759cdad4a52","features_1_heading":"Labore quis aliquip fugiat deserunt non do enim magna.","_features_1_heading":"field_64759cced4a51","features_1_copy":"Irure velit enim dolore elit ullamco Lorem amet aliquip occaecat ipsum proident. Do eu exercitation reprehenderit do laboris aliqua eu aliquip eu ea tempor sunt. Fugiat cillum cillum officia aliqua incididunt ex occaecat quis exercitation ad eiusmod cupidatat officia. Cillum consequat anim esse culpa.","_features_1_copy":"field_64759cdad4a52","features_2_heading":"Anim minim nostrud ipsum velit.","_features_2_heading":"field_64759cced4a51","features_2_copy":"Irure velit enim dolore elit ullamco Lorem amet aliquip occaecat ipsum proident. Do eu exercitation reprehenderit do laboris aliqua eu aliquip eu ea tempor sunt. Fugiat cillum cillum officia aliqua incididunt ex occaecat quis exercitation ad eiusmod cupidatat officia. Cillum consequat anim esse culpa.","_features_2_copy":"field_64759cdad4a52","features_3_heading":"Anim minim nostrud ipsum velit.","_features_3_heading":"field_64759cced4a51","features_3_copy":"Irure velit enim dolore elit ullamco Lorem amet aliquip occaecat ipsum proident. Do eu exercitation reprehenderit do laboris aliqua eu aliquip eu ea tempor sunt. Fugiat cillum cillum officia aliqua incididunt ex occaecat quis exercitation ad eiusmod cupidatat officia. Cillum consequat anim esse culpa.","_features_3_copy":"field_64759cdad4a52","features":4,"_features":"field_64759c96d4a50","columns":"4","_columns":"field_66456ae432ad1"},"align":"full","mode":"preview"} /-->

<!-- wp:acf/logo-cloud {"name":"acf/logo-cloud","data":{"heading_text":"This is a Logo Cloud Block","_heading_text":"field_64af639d1da5e","heading_type":"h2","_heading_type":"field_64af63d01da5f","heading":"","_heading":"field_647593b1d10df","logos":["113","112","111","110","109","108","107","106"],"_logos":"field_647593bfd10e0","columns":"4","_columns":"field_664568266f2e7"},"align":"full","mode":"preview"} /-->
